# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "813fd5f2b7ad1046bd3bb049b86f9dfe"
name = "Commercive"
handle = "Commercive"
application_url = "https://app.commercive.co"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2024-10"

[[webhooks.subscriptions]]
compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
uri = "https://app.commercive.co/webhooks"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_fulfillments,read_inventory,read_locations,read_orders,read_products,write_fulfillments,write_inventory,write_orders,write_products,read_customers"

[auth]
redirect_urls = [
  "https://app.commercive.co/auth/callback",
  "https://app.commercive.co/auth/shopify/callback",
  "https://app.commercive.co/api/auth/callback"
]

[pos]
embedded = false
